.gitignore, command_parser.go, command_parser_test.go, config.go, config_test.go, faults.go, log.go, log_test.go, main.go, process.go, process_group.go, process_group_test.go, process_manager.go, process_manager_test.go, string_expression.go, string_expression_test.go, supervisor.go, xmlrpc.go
- updated config to allow multiple processes to start for the same program
- go fmt on the entire project
=> updated config to allow multi processes + fmt

circle.yml
Now you can use CircleCI to build the project and have executables to several OS's and been upload automatically to Github Releases so users can download binaries.
=> Creating a circle.yml file

config.go, config_test.go, log.go, log_test.go, main.go, pdeathsig_linux.go, pdeathsig_other.go, process.go, process_group.go, process_manager.go, string_expression.go, supervisor.go, xmlrpc.go
1) Fix the -c flag;
2) Make the program panic instead of exit silently;
3) gofmt.
=> A few fixes.

README.md, process.go
So many log files, for our dev env, redirect_stderr is useful
=> Add redirect_stderr

xmlrpc.go
Still has an error about http socket reuse, but call actually works now :D
=> Reload>ReloadConfig

.gitignore, config.go, ctl.go, log.go, log_test.go, main.go, process.go, process_manager.go, supervisor.go, xmlrpc-client.go
I had to use your daemon in Python 3 only environment. And it is known for original daemon not to work with Python 3.
So I had to implement a subset of client commands to control daemon. I implemented `start`, `stop` and `status` commands.
If anyone interested in this here is PM )
=> Added reduced client functionality

supervisor.go
Commands with 'all' expect a different returns, more like a Fault than ProcessInfo.
Before, when using 'supervisorctl stop all', we got:
> $ supervisorctl stop all
error: <type 'exceptions.KeyError'>, 'status': file: /usr/lib/python2.7/dist-packages/supervisor/supervisorctl.py line: 690
=> Fixing returns of 'clear all' / 'stop all' / 'start all'

main.go, supervisor.go
Restarting and shutdown command weren't handled, I added a way to have it working.
Not sure if it's the best way to do it, but it's working :)
=> Handle restart and shutdown command

events.go, events_test.go, process.go
Hey!
I just did a:
```sh
sed -i s_createPorcess_createProcess_g *.go
```
here.
Nothing too complicated
=> typo in createProcess event function

config/config_test.go
Modifications to config.Load doesn't pass tests
=> fixing tests for config.Load

Dockerfile, README.md
Fix #75
Signed-off-by: Romain Beuque <romain.beuque@gmail.com>
=> Adding Dockerfile support

main.go
Fix #76
Signed-off-by: Romain Beuque <romain.beuque@gmail.com>
=> fix(panic): soft failing when command-line args are not provided

.travis.yml, README.md, config/config.go, config/process_group.go, config/process_sort.go, content_checker.go, daemonize.go, daemonize_windows.go, events/events.go, events/events_test.go, logger/log.go, pidproxy/pidproxy.go, pidproxy/signal.go, pidproxy/signal_windows.go, process/path.go, process/pdeathsig_windows.go, process/process.go, process/process_manager.go, supervisor.go, types/comm-types.go, xmlrpc.go, xmlrpcclient/xmlrpc-client.go
I launched the project against gometalinter and fixed all majors issues that have been reported.
Also added a after_script step on travis.yml to auto-run gometalinter after unit tests, to check if code introduces new errors.
This will not produce failing tests as there is remaining errors to fix (golint checking for comment on exported method...)
=> fixing major reports from gometalinter

Dockerfile, Dockerfile.github
Results in a slightly smaller build but should also create a more portable compilation.
Works on my end / in my docker builds but they're alpine based.
=> From scratch static builds

logger/log.go
I guess this was added by accident.
=> Remove debug logs

process/process_manager.go
=> StopAllProcesses in parallel

go.mod, process/process.go
Reverts ochinchina/supervisord#171
=> Revert "fixed a problem which the process start failed and enter a dead cycle"

ctl.go
I tried to fix this problem, and I'm glad to futher modify if anything could be better.Thanks.
=> fixed ctl panic problem #176

webgui/index.html
fix:on window,index.html program status error
=> fix index.html program status

process/process.go, supervisor.go
Fix https://github.com/ochinchina/supervisord/issues/223
=> Fix cond signal

README.md
Original README.md lacks of ini-parameters description and contain outdated build instructions.
There are some typos on stylistic incorrectness there too.
This PR proposes changes that will correct detected documentation issues, but i'm not sure about some parameters and would like to describe them according what they should actually do.
Please, comment this PR so i can complete this PR.
=> Assorted fixes in README.md

README.md, config_template.go
fixes https://github.com/ochinchina/supervisord/issues/251
=> fix logrotate camel case

config/config.go, config/config_test.go, config/process_group.go, config/process_sort.go, config/process_sort_test.go, config/string_expression.go, config_template.go, content_checker.go, ctl.go, daemonize.go, events/events.go, faults/faults.go, logger/log.go, logger/log_unix.go, main.go, process/command_parser.go, process/command_parser_test.go, rlimit.go, supervisor.go, xmlrpcclient/xmlrpc-client.go
=> Style and typo fixes.

README.md, go.mod, service.go
add support of registering service on win/*nix/darwin
eg:
```
sudo supervisord service install -c full_path_to_conf_file
sudo supervisord service uninstall
supervisord service start
supervisord service stop
```
=> register go-supervisord service

process/process.go
=> fix: add killwaitsecs for waiting the force kill exit to avoid stop all exit before all processes exits.

xmlrpcclient/xmlrpc-client.go
it will panic when client get version
=> fix: fix panic when client get version

README.md, config/config.go, config_template.go, go.mod, go.sum, process/process.go
support envfiles in program
https://github.com/ochinchina/supervisord/issues/306
https://github.com/ochinchina/supervisord/issues/59
=> feat: support envfiles in program

main.go, rest-rpc.go, supervisor.go, xmlrpc.go
do not run startHTTPServer() when reload
=> change reload behavior, to behave more like python-supervisor reload

go.mod, go.sum
this update is to fix the CVE-2024-24786
=> fix cve CVE-2024-24786

version.go
```bash
go build -ldflags '-w -s -X main.VERSION=abc -X main.COMMIT=efg' -o supervisord
./supervisord version
Version: abc
Commit: efg
```
=> feat: add commit info to version command
