process.go
Hello,
I found some issues that make supervisord crash (nil pointer exception)
To reproduce, use a supervisord.conf with invalid program path for instance, program will crash instantly. When you ```supervisorctl status``` it will exit immediately.
If you have some comments, please feel free.
Romain
=> Some corners case when programs fails

config.go, process.go
It might not seem like much, but if I want to share a config with coworkers, not all of them have the same GOPATH
For example
```
[program:balancer]
command=balancer --debug
directory=%(ENV_GOPATH)s/src/git.lab/usvc/balancer
stdout_logfile=log/balancer.log
redirect_stderr=true
stdout_logfile_maxbytes=1MB
```
=> Allow environment variable substitution in paths

log.go
Daemon want to delete file from 0 to max backups, but if rotate haven't been processed, it fails
> supervisor> clear worker
error: <type 'exceptions.ValueError'>, Unknown result code -32500 for worker: file: /usr/lib/python2.7/dist-packages/supervisor/supervisorctl.py line: 988
Also, returning the correct error to be more transparent.
=> Clear all logs file should stop at the max rotated file number

config.go, config_test.go
Hey!
Practical example of the bug fix here:
```sh
rbeuque$ TEST="hello world" sleep 220 &
rbeuque$ xargs -n 1 -0 < /proc/6872/environ | head
TEST=hello world
```
No quotes with normal bash behaviour, but we have some with supervisord
=> Environment variable doesn't need to be escaped

xmlrpc-client.go
If XmlRPCClient response code is not 2xx, return the error message.
eg, if request without `username` & `password`, 401 will be returned.
```
Bad Response code: 401
```
=> validate XmlRPCClient response code

supervisor.go
It seems the xmlrpc library does not work with `int64`.
=> Fix `getProcessInfo` return empty timestamp

.goreleaser.yml, .travis.yml
Using travis-ci to auto-launch go test on every pull-requests that are
issued on repository.
after-success part is only trigger if commit is tagged on repository
with a version, so we can auto-release a binary with goreleaser on
GitHub releases part of the repository.
Exemple here for release that have been pushed by travis-ci: https://github.com/Rbeuque74/supervisord/releases
=> Adding .travis.yml and .goreleaser.yml

Gopkg.lock, Gopkg.toml, config/config.go, daemonize.go, events/events.go, main.go, process/process.go, process/process_manager.go, signals/signal_windows.go, supervisor.go, xmlrpc.go
According to note in https://github.com/sirupsen/logrus/blob/master/README.md, all imported package names should be lowercase to avoid issues when adding them via `dep` command
=> Imported package names should be lowercase

config/config.go
Fix a fatal bug: remove program from config just by its program name without 'program:' prefix
=> Fix: remove program from config without 'program:' prefix

supervisor.go
add missed method `TailProcessStderrLog` which is already registered in the `xmlrpc.go`
=> add missed method `TailProcessStderrLog`

go.mod, process/process.go
```bash
ERRO[2019-12-28T22:15:27+08:00] fail to start program because retry times is greater than 3  program=new_rabbbitmq_2
DEBU[2019-12-28T22:15:32+08:00] wait program exit                             program=new_rabbbitmq_2
INFO[2019-12-28T22:15:32+08:00] exit status 1                                 program=new_rabbbitmq_2
DEBU[2019-12-28T22:15:32+08:00] wait program exit                             program=new_rabbbitmq_2
INFO[2019-12-28T22:15:32+08:00] exit status 1                                 program=new_rabbbitmq_2
DEBU[2019-12-28T22:15:32+08:00] wait program exit                             program=new_rabbbitmq_2
INFO[2019-12-28T22:15:32+08:00] exit status 1                                 program=new_rabbbitmq_2
ERRO[2019-12-28T22:15:32+08:00] fail to start program because …
```
=> fixed a problem which the process start failed and enter a dead cycle

config/config.go
I've ecountered several times when users have mistakes writing environment vars expressions in supervisord.conf, and the troubleshooting process is annoying and ineffective, I believe we need some log messages here.
=> add env parse error logs for users' troubleshooting

config/config.go
The current version has a bug that `%(process_num)d` in command field is always parsed as 1. This is caused by incorrectly set section value of "command" after each parse. This PR fixes this bug.
Signed-off-by: Yilun <zyl.skysniper@gmail.com>
=> Fix process_num in command field always parsed as 1

Dockerfile
Needed to build my own image cause of arm64 support, but the current Dockerfile didn't worked for me.
This changes works fine for me https://github.com/users/shyim/packages/container/package/supervisord
Also, your docker image seems currently out of date. If you need help, let me know 😊
=> Add missing dependencies for building docker image

logger/log_windows.go, pidproxy/signal_windows.go
The installSignal function was named incorrectly causing the build to fail.
=> Rename install_signal and add props to syslogger for Windows build

Dockerfile
With the current setting of `GOPROXY=direct`, gopkg.in was directly accessed for downloading go mod packages and that server has been flaky, sometimes returning HTTP 502 messages.
This PR removes override of GOPROXY and GOSUMDB env variables. This will allow `go build` to use the [default proxy provided by google](https://proxy.golang.org/). Using the checksum db to verify the downloaded go mod packages is also just good practice so turning it back on was part of this change.
As a result of using the default proxy provided by google, build times of the docker image should reduce. Previously it took me 41s, but with this change it takes 7s.
=> use default GOPROXY and GOSUMDB for go build

go.mod, go.sum, main.go
When user runs `supervisord -c my.conf ctl`, the parser also returns `flags.ErrCommandRequired`, which causes the `runServer` code executed incorrectly, it would cause confused behaviors, and re-create the unix socket, then `supervisord -c my.conf ctl status` won't work anymore.
This PR uses `parser.Command.SubcommandsOptional` and `parser.CommandHandler` to handle the sub-command behavior correctly.
* `supervisord -c my.conf`:  triggers our default handler and do `runServer`
* `supervisord -c my.conf ctl`: triggers `fmt.Fprintf(os.Stderr, "error when parsing command: %s\n", err)`
* `supervisord -c my.conf ctl status`: triggers the ctl-status sub-command correctly
=> Fix no sub-command bug

process/process.go
I was wondering why my restart file pattern did not work and found out that it was because of the difference between documentation and code. I suggest we use restart_file_pattern because it is closer to proper English and corresponds to the other restart config entries. Here is my tiny pull request.
There is also an issue mentioning that problem: https://github.com/ochinchina/supervisord/issues/316. I suppose it could be closed when this is merged.
=> Rename config entry to restart_file_pattern

xmlrpcclient/xml_processor.go, xmlrpcclient/xmlrpc-client.go
check [this](https://github.com/ZhuzhuNo3/supervisord/raw/test/display_groups_change/supervisord_test.tar.gz) for test.
execute `./run.sh`
```
+ ./tool.sh
+ sleep 3
+ ln -sf ../supervisor_bak/test1.conf ../supervisor_bak/test2.conf ../supervisor_bak/test3.conf ../supervisor_bak/test4.conf ./supervisor/.
+ ./tool.sh reload
Added Groups: test2,test1,test3,test4
+ sleep 3
+ rm -rf ./supervisor/test1.conf ./supervisor/test2.conf ./supervisor/test3.conf
+ ln -sf ../supervisor_bak/test3_change.conf ./supervisor/.
+ ./tool.sh reload
Changed Groups: test3
Removed Groups: test2,test1
+ sleep 3
+ rm -rf ./supervisor/test3_change.conf ./supervisor/test4.conf
+ ln -sf ../supervisor_bak/test1.conf ../supervisor_bak/test2.conf ../supervisor_bak/test3.conf ./supervisor/.
+ ./tool.sh reload
Added Groups: …
```
=> fix: Changes for multiple groups are not displayed correctly

xmlrpc.go
Hello !
I encountered this issue while running supervisord with the env variable `LOG_FORMAT=json` :
```toml
[program:workload]
command = /bin/bash -c "sleep 110000"
stdout_logfile = /dev/stdout
stderr_logfile = /dev/stderr
[inet_http_server]
port=0.0.0.0:1025
username=test
password=test
```
```
{"file":"/supervisor.conf","level":"info","msg":"load configuration from file","time":"2024-12-10T09:11:30Z"}
/dev
```
The debug print was not in json and I believe may have been used for debugging purpose.
=> fix(log): remove useless println

config/config.go, process/process.go
parseEnv in config.go will panic if `s` is empty. 
eg:
```
envs = parseEnv("")
envs = parseEnv("A")
envs = parseEnv("A=")
```
fix with index check
=> fix index out of range when parsing empty env

ctl.go, xmlrpcclient/xmlrpc-client.go
Some errors are silently discarded. This should not happen.
Changes:
- exit code for all remote call errors
- print error to stderr
=> [fix] do not discard errors
